@base_address = http://localhost:3000/api/auth 

POST {{base_address}}/signup 
Content-Type : application/json

{
    "email": "john@example.com",
    "password": "John@123"
}

###
POST {{base_address}}/login 
Content-Type : application/json

{
    "username": "john@example.com",
    "password": "John@123"
}

###
POST {{base_address}}/logout

### Refresh token
POST {{base_address}}/logout
