@base_address = http://localhost:3000/api/people

GET {{base_address}}

###
GET {{base_address}}/4

###
POST {{base_address}}
Content-Type: application/json

{
    "firstName" :"Ravindra",
    "lastName": "Devrani"
}

###
PUT {{base_address}}/4
Content-Type: application/json

{
    "id":4,
    "firstName" :"Mahendra",
    "lastName": "Bahubali"
}
