@base_address = http://localhost:3000/api/people
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDk2NTIzOTEsImV4cCI6MTc0OTY1MjQ1MX0.1J7aYNnb3QKwiVU98LZ4N35cTYome5fIBNv5JNWGjjI

GET {{base_address}}
Authorization: Bearer {{jwt}}

###
GET {{base_address}}/4
Authorization: Bearer {{jwt}}

###
POST {{base_address}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "firstName" :"Johny",
    "lastName": "Bravo"
}

###
PUT {{base_address}}/4
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "firstName" :"Mahesh",
    "lastName": "Kumar"
}

###
DELETE  {{base_address}}/5
Authorization: Bearer {{jwt}}
Content-Type: application/json
