@base_address = http://localhost:3000/api/people

GET {{base_address}}

###
GET {{base_address}}/6

###
POST {{base_address}}
Content-Type: application/json

{
    "firstName" :"Ravindra",
    "lastName": "Devrani"
}

###
PUT {{base_address}}/6
Content-Type: application/json

{
    "firstName" :"Amrendra",
    "lastName": "Bahubully"
}

###
DELETE  {{base_address}}/6
Content-Type: application/json
