require("dotenv").config();
const routes = require('./routes');
const express = require("express");
const app = express();
const cors = require('cors');
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(routes);
module.exports = app;
